steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['-q','--batch-mode','package','test']
artifacts:
  objects:
    location: 'gs://features-javac'
    paths: ['extractor/target/features-javac-extractor-latest.jar']